### ISSUE TITLE
kernel modules are being overwritten

### ISSUE THREAD

**Issue by kamikaze** [oglueck/to-gentoo#1]
Are you sure that it is a good idea to overwrite kernel modules in /lib while leaving original kernel in /boot ?

**Comment by oglueck** [comment]
/lib/modules is retained:
see line 111:
echo " - kernel modules"
cp -ra /lib/modules lib/ || true

and see README.md:
To make transition a bit smoother, the following things will be kept / migrated to Gentoo:
- bootloader, the kernel and its modules in /lib/modules
